# Generated by Django 3.1.6 on 2021-02-15 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210212_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sale_amount',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.date(2021, 2, 15)),
        ),
    ]
